### ISSUE TITLE
请问怎么爬ylyk的音频？

### ISSUE THREAD

**Issue by fortinetps** [mikumifa/FuckYouling#1]
Thanks!

**Comment by mikumifa** [comment]
手机抓包就行，友邻的防爬做的很垃圾，能把要vip的也爬下来



---原始邮件---
发件人: "Don ***@***.***&gt;
发送时间: 2024年1月21日(周日) 中午11:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [mikumifa/FuckYouling] 请问怎么爬ylyk的音频？ (Issue #1)




 
Thanks!

**Comment by fortinetps** [comment]
用你的例子能从https://new-app-api.ylyk.com/v1/goods/getAudioCourseGoodsDetail  得到数据，但音频的URL好像是加密编码过的。
譬如我用的是这一集节目做测试《“孔乙己的长衫”走红：年轻人要放弃大学文凭吗？》，"courseGoodsId": "108759",      "albumGoodsId": "108745", 
得到的是这个 "audioFileUrl": "MWqRpp8dE0XabgHzlvXnNlkeWQeJjM6b46uFRLyPiYrEfU0fEGvHpWjnFghBE7zSjVC4EhbCeACmNh9ndoK3X3Gwlj8oiJQW6/NLzY2jI58=",
我知道它对应的是这个音频是这个：https://mv-cdn1.ylyk.com/media/1679805990550_m1679885948975_s36408291.mp3
但我找不到破解的方法，不知道你是否能帮助一下，谢谢！

**Comment by mikumifa** [comment]
最新的我添加了一个写的爬取视频的，供参考， 破解方法是frida脱壳，解安卓包，有点复杂 #2

**Comment by zswallowz** [comment]
太厉害了！问题解决！谢谢你的帮忙！我对Android开发和frida都不熟悉，有空要学习一下。祝你一切顺利！

**Comment by fortinetps** [comment]
太厉害了！问题解决！我对Andrid开发和Frida都不熟悉，需要学习一下！多谢你的帮助！祝你一切顺利！
